version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            export ELODIE_DIR=${PWD}
            export EXIFTOOL_VERSION=13.50
            pip install -r elodie/tests/requirements.txt
            pip install -r elodie/plugins/googlephotos/requirements.txt
            pip install coveralls pytest-cov
            sed -i.bak 's/debug = False/debug = True/g' elodie/constants.py
            wget -O Image-ExifTool-${EXIFTOOL_VERSION}.tar.gz https://files.jmathai.com/elodie/Image-ExifTool-13.50.tar.gz
            gzip -dc Image-ExifTool-${EXIFTOOL_VERSION}.tar.gz  | tar -xf -
            cd Image-ExifTool-${EXIFTOOL_VERSION}
            perl Makefile.PL
            sudo make install
            echo "which exiftool command"
            which exiftool
            cd ${ELODIE_DIR}
      - run:
          name: Run tests
          command: pytest elodie/tests -v --cov=elodie --cov-report=xml
      - run:
          name: Generate coverage
          command: |
            coveralls

workflows:
  ci:
    jobs:
      - build_and_test
